route:
  group_by: [Alertname]
  # Send all notifications to me.
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: 'architectdevops7@gmail.com'
    from: 'architectdevops7@gmail.com'
    smarthost: 'smtp.gmail.com:587'
    auth_username: 'architectdevops7@gmail.com'
    auth_identity: 'architectdevops7@gmail.com'
    auth_password: '*****************'
    send_resolved: true
